name: SoulHive-System
version: 2.0-SNAPSHOT
main: de.soulhive.system.SoulHive
depend: [ProtocolLib, ASkyBlock]
description: The official SoulHive system.
author: dieser1dude
commands:
  none:
  debug:
  motd:
  stats:
  rawbc:
  vanish:
  chatclear:
    aliases: [cc]
  gamemode:
    aliases: [gm]
  giveall:
  item:
    aliases: [i]
  rename:
  speed:
  sudo:
  teamchat:
    aliases: [tc]
  ping:
  repair:
    aliases: [fix]
  skull:
    aliases: [head]
  stack:
  top:
  workbench:
    aliases: [wb]
  clearinventory:
    aliases: [ci, clear]
  spawn:
    aliases: [hub, lobby, l]
  fly:
  trash:
    aliases: [abfall]
  fill:
  cook:
    aliases:
  bottle:
  anvil:
    aliases: [amboss]
  enchanter:
    aliases: [zaubertisch]
  day:
  enderchest:
    aliases: [ec]
  feed:
  heal:
  hat:
    aliases: [hut]
  report:
  spectate:
    aliases: [spec]