name: SoulHive-System
version: 2.0-SNAPSHOT
main: de.soulhive.system.SoulHive
depend: [ProtocolLib, ASkyBlock]
description: The official SoulHive system.
author: dieser1dude
commands:
  none:
  debug:
  motd:
  stats:
  rawbc:
  vanish:
  chatclear:
    aliases: [cc]
  gamemode:
    aliases: [gm]
  giveall:
  item:
    aliases: [i]
  rename:
  speed:
  sudo:
  teamchat:
    aliases: [tc]
  ping:
  repair:
  skull:
  stack:
  top:
  workbench:
  clearinventory:
    aliases: [ci, clear]
  spawn:
    aliases: [hub, lobby, l]